// plan: specs/api/Auth.api-plan.json
// Generated by api-test-generator — review before committing

import { test, expect } from './helpers/api-logger';
import { expectStatus, wrapFrameworkError } from './helpers/status-assert';

const AUTH_TOKEN = process.env.API_AUTH_TOKEN || '';

function authHeaders(token: string = AUTH_TOKEN): Record<string, string> {
  return token ? { Authorization: `Bearer ${token}` } : {};
}

// ✅ Unique email helper — prevents "Email already registered" conflicts across runs
function uniqueEmail(prefix: string = 'testuser'): string {
  return `${prefix}+${Date.now()}@example.com`;
}

test.describe('Auth', () => {
  test.describe('POST /register/', () => {
    test('[Positive] Register user with valid email, password, and name', async ({ request }) => {
      const data = {
        email: uniqueEmail('testnew'),
        password: 'SecurePassword123!',
        name: 'Test User',
      };

      await test.step('Send POST /register/', async () => {
        const response = await request.post('/register/', {
          data,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 201, 'POST /register/ positive case');
        });
      });
    });

    test('[Validation] Register user missing required name', async ({ request }) => {
      const data = {
        email: uniqueEmail('testnew'),
        password: 'SecurePassword123!',
        // name is missing — required field
      };

      await test.step('Send POST /register/', async () => {
        const response = await request.post('/register/', {
          data,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 422, 'POST /register/ validation error: missing name');
        });
      });
    });

    test('[Validation] Register user with malformed email', async ({ request }) => {
      const data = {
        email: 'not-an-email-format', // intentionally invalid — uniqueEmail() not needed
        password: 'SecurePassword123!',
        name: 'Test User',
      };

      await test.step('Send POST /register/', async () => {
        const response = await request.post('/register/', {
          data,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 422, 'POST /register/ validation error: malformed email');
        });
      });
    });

    test('[SchemaValidation] Verify register response matches RegisterResponse schema', async ({ request }) => {
      const data = {
        email: uniqueEmail('testnew'),
        password: 'SecurePassword123!',
        name: 'Test User',
      };

      await test.step('Send POST /register/', async () => {
        const response = await request.post('/register/', {
          data,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 201, 'POST /register/ schema validation');
        });

        await test.step('Assert response schema', async () => {
          try {
            const body = await response.json();
            expect(body).toHaveProperty('id');
            expect(typeof body.id).toBe('number');
            expect(body).toHaveProperty('email');
            expect(typeof body.email).toBe('string');
            expect(body).toHaveProperty('name');
            expect(typeof body.name).toBe('string');
            expect(body).toHaveProperty('is_active');
            expect(typeof body.is_active).toBe('boolean');
            expect(body).toHaveProperty('registered_as');
            expect(typeof body.registered_as).toBe('string');
          } catch (err) {
            wrapFrameworkError('parsing RegisterResponse schema', err);
          }
        });
      });
    });
  });

  test.describe('GET /register/verify-email', () => {
    test('[Positive] Verify email link with valid token query parameter', async ({ request }) => {
      const params = {
        token: 'valid_verification_token_1234567890abcdef',
      };

      await test.step('Send GET /register/verify-email', async () => {
        const response = await request.get('/register/verify-email', {
          params,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 200, 'GET /register/verify-email positive case');
        });
      });
    });

    test('[Validation] Verify email link missing token query parameter', async ({ request }) => {
      await test.step('Send GET /register/verify-email without token', async () => {
        const response = await request.get('/register/verify-email', {
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 422, 'GET /register/verify-email validation error: missing token');
        });
      });
    });

    test('[Boundary] Verify email link with token shorter than minimum length', async ({ request }) => {
      const params = {
        token: 'short', // Token must be at least 16 characters
      };

      await test.step('Send GET /register/verify-email', async () => {
        const response = await request.get('/register/verify-email', {
          params,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 422, 'GET /register/verify-email boundary error: token too short');
        });
      });
    });
  });

  test.describe('POST /register/resend-verification-email', () => {
    test('[Positive] Resend verification email with valid registered email', async ({ request }) => {
      const data = {
        email: uniqueEmail('testnow'),
      };

      await test.step('Send POST /register/resend-verification-email', async () => {
        const response = await request.post('/register/resend-verification-email', {
          data,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 200, 'POST /register/resend-verification-email positive case');
        });
      });
    });

    test('[Validation] Resend verification email missing email', async ({ request }) => {
      const data = {
        // email is missing — required field
      };

      await test.step('Send POST /register/resend-verification-email', async () => {
        const response = await request.post('/register/resend-verification-email', {
          data,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 422, 'POST /register/resend-verification-email validation error: missing email');
        });
      });
    });

    test('[Validation] Resend verification email with invalid email format', async ({ request }) => {
      const data = {
        email: 'not-an-email-format', // intentionally invalid — uniqueEmail() not needed
      };

      await test.step('Send POST /register/resend-verification-email', async () => {
        const response = await request.post('/register/resend-verification-email', {
          data,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 422, 'POST /register/resend-verification-email validation error: invalid email format');
        });
      });
    });

    test('[SchemaValidation] Verify resend verification email response matches ResendVerificationResponse schema', async ({ request }) => {
      const data = {
        email: uniqueEmail('testnow'),
      };

      await test.step('Send POST /register/resend-verification-email', async () => {
        const response = await request.post('/register/resend-verification-email', {
          data,
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 200, 'POST /register/resend-verification-email schema validation');
        });

        await test.step('Assert response schema', async () => {
          try {
            const body = await response.json();
            expect(body).toHaveProperty('message');
            expect(typeof body.message).toBe('string');
            expect(body).toHaveProperty('verification_email_sent');
            expect(typeof body.verification_email_sent).toBe('boolean');
          } catch (err) {
            wrapFrameworkError('parsing ResendVerificationResponse schema', err);
          }
        });
      });
    });
  });

  test.describe('POST /register/resend-verification', () => {
    test('[Positive] Resend verification email while authenticated', async ({ request }) => {
      await test.step('Send POST /register/resend-verification', async () => {
        const response = await request.post('/register/resend-verification', {
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 200, 'POST /register/resend-verification positive case (authenticated)');
        });
      });
    });

    test('[Authentication] Resend verification email with missing auth token', async ({ request }) => {
      await test.step('Send POST /register/resend-verification without auth token', async () => {
        const response = await request.post('/register/resend-verification', {
          headers: {
        Authorization: '', // ✅ explicitly overrides any global extraHTTPHeaders
            },              // Empty token = no Authorization header
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 401, 'POST /register/resend-verification authentication error: missing token');
        });
      });
    });

    test('[SchemaValidation] Verify resend verification response matches ResendVerificationResponse schema', async ({ request }) => {
      await test.step('Send POST /register/resend-verification', async () => {
        const response = await request.post('/register/resend-verification', {
          headers: authHeaders(),
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 200, 'POST /register/resend-verification schema validation');
        });

        await test.step('Assert response schema', async () => {
          try {
            const body = await response.json();
            expect(body).toHaveProperty('message');
            expect(typeof body.message).toBe('string');
            expect(body).toHaveProperty('verification_email_sent');
            expect(typeof body.verification_email_sent).toBe('boolean');
          } catch (err) {
            wrapFrameworkError('parsing ResendVerificationResponse schema', err);
          }
        });
      });
    });
  });

  test.describe('POST /login/', () => {
    test('[Positive] Login for access token with valid username and password', async ({ request }) => {
      await test.step('Send POST /login/', async () => {
        const response = await request.post('/login/', {
          form: {          // ✅ use `form` instead of `data` — Playwright sets Content-Type automatically
            username: 'junaid@gmail.com',
            password: '12345',
          },
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 200, 'POST /login/ positive case');
        });
      });
    });

    test('[Validation] Login for access token missing password', async ({ request }) => {
      const data = new URLSearchParams();
      data.append('username', 'junaid@gmail.com');
      // password is missing — required field

      await test.step('Send POST /login/', async () => {
        const response = await request.post('/login/', {
          data,
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
          },
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 422, 'POST /login/ validation error: missing password');
        });
      });
    });

    test('[Validation] Login for access token with invalid grant_type', async ({ request }) => {
      const data = new URLSearchParams();
      data.append('username', 'junaid@gmail.com');
      data.append('password', '12345');
      data.append('grant_type', 'invalid_grant_type');

      await test.step('Send POST /login/', async () => {
        const response = await request.post('/login/', {
          data,
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
          },
        });

        await test.step('Assert response status', async () => {
          await expectStatus(response, 422, 'POST /login/ validation error: invalid grant_type');
        });
      });
    });

    test('[SchemaValidation] Verify login access token response matches LoginAccessTokenResponse schema', async ({ request }) => {
        await test.step('Send POST /login/', async () => {
          const response = await request.post('/login/', {
            form: {          // ✅ use `form` instead of `data`
              username: 'junaid@gmail.com',
              password: '12345',
            },
          });

          await test.step('Assert response status', async () => {
            await expectStatus(response, 200, 'POST /login/ schema validation');
          });

          await test.step('Assert response schema', async () => {
            try {
              const body = await response.json();
              expect(body).toHaveProperty('access_token');
              expect(typeof body.access_token).toBe('string');
              expect(body).toHaveProperty('email_verified');
              expect(typeof body.email_verified).toBe('boolean');
            } catch (err) {
              wrapFrameworkError('parsing LoginAccessTokenResponse schema', err);
            }
          });
        });
      });

  });
});